using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using VideoCortex.Core.Services.Config;

namespace VideoCortex.Core.Services.Transcripts;

/// <summary>
/// Apify <c>streamers/youtube-scraper</c>-backed transcript source. One call to the
/// <c>run-sync-get-dataset-items</c> endpoint returns the scraped video object inline — giving
/// us the transcript plus title, channel, description, duration, counts, and thumbnail in a
/// single hit. Fails cleanly (returns a failed <see cref="Transcript"/>, never throws across
/// the seam) on a missing token, a non-2xx response, a timeout, or an empty dataset.
/// </summary>
public sealed class ApifyTranscriptSource : ITranscriptSource
{
    private const string ActorRunSyncEndpoint =
        "https://api.apify.com/v2/acts/streamers~youtube-scraper/run-sync-get-dataset-items";

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    private readonly HttpClient _http;
    private readonly ApifySettings _settings;
    private readonly ILogger<ApifyTranscriptSource> _logger;

    public ApifyTranscriptSource(
        HttpClient http,
        IOptions<ApifySettings> settings,
        ILogger<ApifyTranscriptSource> logger)
    {
        _http = http;
        _settings = settings.Value;
        _logger = logger;

        // Per-call timeout governs the synchronous run; override HttpClient's 100s default.
        _http.Timeout = TimeSpan.FromSeconds(_settings.RunTimeoutSeconds);
    }

    public async Task<Transcript> FetchAsync(string videoId, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(videoId))
            return Transcript.Failure("Video ID is required.");

        if (string.IsNullOrWhiteSpace(_settings.Token))
            return Transcript.Failure("Apify token is not configured. Set Apify:Token in user-secrets or Settings.");

        var url = $"{ActorRunSyncEndpoint}?token={Uri.EscapeDataString(_settings.Token)}";
        var requestBody = new ApifyRequestBody
        {
            StartUrls = new[] { new ApifyStartUrl { Url = $"https://www.youtube.com/watch?v={videoId}" } },
            DownloadSubtitles = true,
            PreferAutoGeneratedSubtitles = _settings.PreferAutoGenerated,
            SubtitlesLanguage = _settings.PreferredLanguage,
        };

        try
        {
            using var content = new StringContent(
                JsonSerializer.Serialize(requestBody, JsonOpts), Encoding.UTF8, "application/json");

            using var response = await _http.PostAsync(url, content, ct);

            if (!response.IsSuccessStatusCode)
            {
                var body = await response.Content.ReadAsStringAsync(ct);
                _logger.LogWarning("Apify returned {Status} for video {VideoId}: {Body}",
                    response.StatusCode, videoId, body);
                return Transcript.Failure($"Apify {(int)response.StatusCode}: {body}");
            }

            var stream = await response.Content.ReadAsStreamAsync(ct);
            var items = await JsonSerializer.DeserializeAsync<List<ApifyScraperItem>>(stream, JsonOpts, ct);

            var item = items?.FirstOrDefault();
            if (item is null)
                return Transcript.Failure("Apify returned an empty dataset.");

            var subtitle = SelectBestSubtitle(item.Subtitles);
            var transcriptText = subtitle is null
                ? null
                : SrtConverter.ConvertSrtToPrdFormat(subtitle.Srt ?? string.Empty);
            var hasTranscript = !string.IsNullOrWhiteSpace(transcriptText);

            var seconds = DurationParser.ParseToSeconds(item.Duration);

            return new Transcript(
                Success: true,
                TranscriptText: hasTranscript ? transcriptText : null,
                TranscriptLang: subtitle?.Language,
                HasTranscript: hasTranscript,
                Title: item.Title,
                ChannelTitle: item.ChannelName,
                Description: item.Text,
                DurationSeconds: seconds > 0 ? seconds : null,
                ViewCount: item.ViewCount,
                LikeCount: item.Likes,
                CommentsCount: item.CommentsCount,
                ThumbnailUrl: item.ThumbnailUrl,
                ErrorMessage: null);
        }
        catch (TaskCanceledException tcex) when (!ct.IsCancellationRequested)
        {
            _logger.LogError(tcex, "Apify call timed out for video {VideoId}", videoId);
            return Transcript.Failure($"Apify call timed out after {_settings.RunTimeoutSeconds}s.");
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            _logger.LogError(ex, "Unexpected error fetching transcript for video {VideoId}", videoId);
            return Transcript.Failure(ex.Message);
        }
    }

    private static ApifySubtitle? SelectBestSubtitle(List<ApifySubtitle>? subtitles)
    {
        if (subtitles is null || subtitles.Count == 0)
            return null;

        // Prefer a manual English caption, then any English, then anything with SRT content.
        return subtitles.FirstOrDefault(s =>
                   string.Equals(s.Language, "en", StringComparison.OrdinalIgnoreCase)
                   && !string.Equals(s.Type, "auto_generated", StringComparison.OrdinalIgnoreCase)
                   && !string.IsNullOrWhiteSpace(s.Srt))
               ?? subtitles.FirstOrDefault(s =>
                   string.Equals(s.Language, "en", StringComparison.OrdinalIgnoreCase)
                   && !string.IsNullOrWhiteSpace(s.Srt))
               ?? subtitles.FirstOrDefault(s => !string.IsNullOrWhiteSpace(s.Srt));
    }

    // -- Apify request/response DTOs (only the fields we use) ----------------------------------

    private sealed class ApifyRequestBody
    {
        [JsonPropertyName("startUrls")] public ApifyStartUrl[] StartUrls { get; set; } = Array.Empty<ApifyStartUrl>();
        [JsonPropertyName("downloadSubtitles")] public bool DownloadSubtitles { get; set; }
        [JsonPropertyName("preferAutoGeneratedSubtitles")] public bool PreferAutoGeneratedSubtitles { get; set; }
        [JsonPropertyName("subtitlesLanguage")] public string SubtitlesLanguage { get; set; } = "en";
    }

    private sealed class ApifyStartUrl
    {
        [JsonPropertyName("url")] public string Url { get; set; } = string.Empty;
    }

    private sealed class ApifyScraperItem
    {
        [JsonPropertyName("title")] public string? Title { get; set; }
        [JsonPropertyName("channelName")] public string? ChannelName { get; set; }
        [JsonPropertyName("text")] public string? Text { get; set; }
        [JsonPropertyName("duration")] public string? Duration { get; set; }
        [JsonPropertyName("viewCount")] public long? ViewCount { get; set; }
        [JsonPropertyName("likes")] public long? Likes { get; set; }
        [JsonPropertyName("commentsCount")] public long? CommentsCount { get; set; }
        [JsonPropertyName("thumbnailUrl")] public string? ThumbnailUrl { get; set; }
        [JsonPropertyName("subtitles")] public List<ApifySubtitle>? Subtitles { get; set; }
    }

    private sealed class ApifySubtitle
    {
        [JsonPropertyName("language")] public string? Language { get; set; }
        [JsonPropertyName("type")] public string? Type { get; set; }
        [JsonPropertyName("srt")] public string? Srt { get; set; }
    }
}
