namespace VideoCortex.Core.Services.Config;

// Init-property records (not positional) so IConfiguration.Bind / Configure<T> populate them
// cleanly from appsettings.json + the overlay. Each carries its config section name.

/// <summary>Apify transcript-source settings. <c>Token</c> is a secret (blank in source).</summary>
public record ApifySettings
{
    public const string Section = "Apify";

    public string Token { get; init; } = string.Empty;
    public int RunTimeoutSeconds { get; init; } = 300;
    public string PreferredLanguage { get; init; } = "en";
    public bool PreferAutoGenerated { get; init; } = true;
}

/// <summary>
/// OpenAI-compatible LLM endpoint settings. Blank <c>BaseUrl</c> falls back to hosted OpenAI;
/// point it at Ollama's <c>/v1</c> to run locally. <c>ApiKey</c> is a secret (blank in source).
/// </summary>
public record LlmSettings
{
    public const string Section = "Llm";

    public string Model { get; init; } = "gpt-4o-mini";
    public string? BaseUrl { get; init; }
    public string? ApiKey { get; init; }
    public int RequestTimeoutSeconds { get; init; } = 600;
}

/// <summary>Where the on-disk OKF-HTML libraries are written.</summary>
public record LibrarySettings
{
    public const string Section = "Library";

    public string RootPath { get; init; } = VideoCortexPaths.DefaultLibraryRoot;
}

/// <summary>Transcript worker tunables.</summary>
public record TranscriptWorkerSettings
{
    public const string Section = "TranscriptWorker";

    public int IdlePollSeconds { get; init; } = 10;
    public int MaxRetryAttempts { get; init; } = 3;
}

/// <summary>Summary worker tunables.</summary>
public record SummarySettings
{
    public const string Section = "Summary";

    public int IdlePollSeconds { get; init; } = 10;
    public int MaxRetryAttempts { get; init; } = 3;
}

/// <summary>Report worker tunables. Debounce coalesces rapid adds before regenerating.</summary>
public record ReportSettings
{
    public const string Section = "Report";

    public int IdlePollSeconds { get; init; } = 10;
    public int CoalesceDebounceSeconds { get; init; } = 10;
    public int MaxRetryAttempts { get; init; } = 3;
}
