using FluentAssertions;
using Microsoft.Extensions.Configuration;
using VideoCortex.Core.Services.Config;

namespace VideoCortex.Tests;

public class PathsTests
{
    [Fact]
    public void DbPath_EndsWith_Expected()
        => VideoCortexPaths.DbPath.Should().EndWith(Path.Combine(".videocortex", "app.db"));

    [Fact]
    public void OverlayPath_EndsWith_Expected()
        => VideoCortexPaths.OverlayPath.Should().EndWith(Path.Combine(".videocortex", "appsettings.Local.json"));

    [Fact]
    public void DefaultLibraryRoot_EndsWith_SecondBrain()
        => VideoCortexPaths.DefaultLibraryRoot.Should().EndWith("SecondBrain");
}

public class SettingsBindingTests
{
    private static IConfiguration Build(Dictionary<string, string?> values)
        => new ConfigurationBuilder().AddInMemoryCollection(values).Build();

    [Fact]
    public void ApifySettings_Bind_From_Config()
    {
        var cfg = Build(new()
        {
            ["Apify:Token"] = "tok",
            ["Apify:RunTimeoutSeconds"] = "120",
            ["Apify:PreferAutoGenerated"] = "false",
        });

        var s = cfg.GetSection(ApifySettings.Section).Get<ApifySettings>()!;
        s.Token.Should().Be("tok");
        s.RunTimeoutSeconds.Should().Be(120);
        s.PreferAutoGenerated.Should().BeFalse();
        s.PreferredLanguage.Should().Be("en"); // default preserved
    }

    [Fact]
    public void LlmSettings_Bind_From_Config()
    {
        var cfg = Build(new()
        {
            ["Llm:Model"] = "llama3",
            ["Llm:BaseUrl"] = "http://localhost:11434/v1",
        });

        var s = cfg.GetSection(LlmSettings.Section).Get<LlmSettings>()!;
        s.Model.Should().Be("llama3");
        s.BaseUrl.Should().Be("http://localhost:11434/v1");
        s.RequestTimeoutSeconds.Should().Be(600); // default preserved
    }

    [Fact]
    public void ReportSettings_Bind_From_Config()
    {
        var cfg = Build(new() { ["Report:CoalesceDebounceSeconds"] = "42" });

        var s = cfg.GetSection(ReportSettings.Section).Get<ReportSettings>()!;
        s.CoalesceDebounceSeconds.Should().Be(42);
        s.IdlePollSeconds.Should().Be(10); // default preserved
    }

    [Fact]
    public void LibrarySettings_Default_RootPath_Is_DefaultLibraryRoot()
    {
        // Empty config leaves the init default intact.
        var s = Build(new()).GetSection(LibrarySettings.Section).Get<LibrarySettings>()
                ?? new LibrarySettings();
        s.RootPath.Should().Be(VideoCortexPaths.DefaultLibraryRoot);
    }
}
